// Code generated by MockGen. DO NOT EDIT.
// Source: goph_keeper/cli/storage (interfaces: IStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_store.go -package=mocks goph_keeper/cli/storage IStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "goph_keeper/cli/entity"
	storage "goph_keeper/cli/storage"
	auth "goph_keeper/pkg/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIStore is a mock of IStore interface.
type MockIStore struct {
	ctrl     *gomock.Controller
	recorder *MockIStoreMockRecorder
	isgomock struct{}
}

// MockIStoreMockRecorder is the mock recorder for MockIStore.
type MockIStoreMockRecorder struct {
	mock *MockIStore
}

// NewMockIStore creates a new mock instance.
func NewMockIStore(ctrl *gomock.Controller) *MockIStore {
	mock := &MockIStore{ctrl: ctrl}
	mock.recorder = &MockIStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStore) EXPECT() *MockIStoreMockRecorder {
	return m.recorder
}

// GetBin mocks base method.
func (m *MockIStore) GetBin(ctx context.Context, userID int, name string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBin", ctx, userID, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBin indicates an expected call of GetBin.
func (mr *MockIStoreMockRecorder) GetBin(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBin", reflect.TypeOf((*MockIStore)(nil).GetBin), ctx, userID, name)
}

// GetLocalUserByLogin mocks base method.
func (m *MockIStore) GetLocalUserByLogin(ctx context.Context, login string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalUserByLogin", ctx, login)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalUserByLogin indicates an expected call of GetLocalUserByLogin.
func (mr *MockIStoreMockRecorder) GetLocalUserByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalUserByLogin", reflect.TypeOf((*MockIStore)(nil).GetLocalUserByLogin), ctx, login)
}

// GetLogoPass mocks base method.
func (m *MockIStore) GetLogoPass(ctx context.Context, userID int, name string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogoPass", ctx, userID, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetLogoPass indicates an expected call of GetLogoPass.
func (mr *MockIStoreMockRecorder) GetLogoPass(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogoPass", reflect.TypeOf((*MockIStore)(nil).GetLogoPass), ctx, userID, name)
}

// GetNotSyncedItems mocks base method.
func (m *MockIStore) GetNotSyncedItems(ctx context.Context) ([]storage.CatalogItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotSyncedItems", ctx)
	ret0, _ := ret[0].([]storage.CatalogItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotSyncedItems indicates an expected call of GetNotSyncedItems.
func (mr *MockIStoreMockRecorder) GetNotSyncedItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotSyncedItems", reflect.TypeOf((*MockIStore)(nil).GetNotSyncedItems), ctx)
}

// StoreBin mocks base method.
func (m *MockIStore) StoreBin(ctx context.Context, userID int, name, storeBin, meta string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBin", ctx, userID, name, storeBin, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBin indicates an expected call of StoreBin.
func (mr *MockIStoreMockRecorder) StoreBin(ctx, userID, name, storeBin, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBin", reflect.TypeOf((*MockIStore)(nil).StoreBin), ctx, userID, name, storeBin, meta)
}

// StoreInitialUserData mocks base method.
func (m *MockIStore) StoreInitialUserData(ctx context.Context, login, pass, phrase string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreInitialUserData", ctx, login, pass, phrase)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreInitialUserData indicates an expected call of StoreInitialUserData.
func (mr *MockIStoreMockRecorder) StoreInitialUserData(ctx, login, pass, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreInitialUserData", reflect.TypeOf((*MockIStore)(nil).StoreInitialUserData), ctx, login, pass, phrase)
}

// StoreLogoPass mocks base method.
func (m *MockIStore) StoreLogoPass(ctx context.Context, userID int, name, storeLogo, storePass, meta string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLogoPass", ctx, userID, name, storeLogo, storePass, meta)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLogoPass indicates an expected call of StoreLogoPass.
func (mr *MockIStoreMockRecorder) StoreLogoPass(ctx, userID, name, storeLogo, storePass, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLogoPass", reflect.TypeOf((*MockIStore)(nil).StoreLogoPass), ctx, userID, name, storeLogo, storePass, meta)
}

// StoreToken mocks base method.
func (m *MockIStore) StoreToken(ctx context.Context, login string, token auth.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreToken", ctx, login, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreToken indicates an expected call of StoreToken.
func (mr *MockIStoreMockRecorder) StoreToken(ctx, login, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreToken", reflect.TypeOf((*MockIStore)(nil).StoreToken), ctx, login, token)
}

// UpdateCatalogItem mocks base method.
func (m *MockIStore) UpdateCatalogItem(ctx context.Context, userID int, dataID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCatalogItem", ctx, userID, dataID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCatalogItem indicates an expected call of UpdateCatalogItem.
func (mr *MockIStoreMockRecorder) UpdateCatalogItem(ctx, userID, dataID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCatalogItem", reflect.TypeOf((*MockIStore)(nil).UpdateCatalogItem), ctx, userID, dataID)
}
