// Code generated by MockGen. DO NOT EDIT.
// Source: goph_keeper/cli/remote (interfaces: IRemote)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_sender.go -package=mocks goph_keeper/cli/remote IRemote
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	remote "goph_keeper/cli/remote"
	auth "goph_keeper/pkg/auth"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRemote is a mock of IRemote interface.
type MockIRemote struct {
	ctrl     *gomock.Controller
	recorder *MockIRemoteMockRecorder
	isgomock struct{}
}

// MockIRemoteMockRecorder is the mock recorder for MockIRemote.
type MockIRemoteMockRecorder struct {
	mock *MockIRemote
}

// NewMockIRemote creates a new mock instance.
func NewMockIRemote(ctrl *gomock.Controller) *MockIRemote {
	mock := &MockIRemote{ctrl: ctrl}
	mock.recorder = &MockIRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRemote) EXPECT() *MockIRemoteMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockIRemote) Auth(ctx context.Context, login, pass string) (auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, login, pass)
	ret0, _ := ret[0].(auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockIRemoteMockRecorder) Auth(ctx, login, pass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockIRemote)(nil).Auth), ctx, login, pass)
}

// GetBinData mocks base method.
func (m *MockIRemote) GetBinData(ctx context.Context, req remote.GetBinRequest) (*remote.GetBinResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinData", ctx, req)
	ret0, _ := ret[0].(*remote.GetBinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinData indicates an expected call of GetBinData.
func (mr *MockIRemoteMockRecorder) GetBinData(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinData", reflect.TypeOf((*MockIRemote)(nil).GetBinData), ctx, req)
}

// GetLogoPass mocks base method.
func (m *MockIRemote) GetLogoPass(ctx context.Context, req remote.GetLogoPassRequest, token string) (*remote.GetLogoPassResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogoPass", ctx, req, token)
	ret0, _ := ret[0].(*remote.GetLogoPassResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogoPass indicates an expected call of GetLogoPass.
func (mr *MockIRemoteMockRecorder) GetLogoPass(ctx, req, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogoPass", reflect.TypeOf((*MockIRemote)(nil).GetLogoPass), ctx, req, token)
}

// Register mocks base method.
func (m *MockIRemote) Register(ctx context.Context, login, pass, phrase string) (auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, pass, phrase)
	ret0, _ := ret[0].(auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIRemoteMockRecorder) Register(ctx, login, pass, phrase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIRemote)(nil).Register), ctx, login, pass, phrase)
}

// SendBinData mocks base method.
func (m *MockIRemote) SendBinData(ctx context.Context, req remote.StoreBin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBinData", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBinData indicates an expected call of SendBinData.
func (mr *MockIRemoteMockRecorder) SendBinData(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBinData", reflect.TypeOf((*MockIRemote)(nil).SendBinData), ctx, req)
}

// SendLogoPass mocks base method.
func (m *MockIRemote) SendLogoPass(ctx context.Context, req remote.StoreLogoPassRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLogoPass", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLogoPass indicates an expected call of SendLogoPass.
func (mr *MockIRemoteMockRecorder) SendLogoPass(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLogoPass", reflect.TypeOf((*MockIRemote)(nil).SendLogoPass), ctx, req)
}
